using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Configuration;
using Moq;
using Moq.Protected;
using Xunit;
using FluentAssertions;
using _10_Filmdatenbank.Application.Services;
using Tvdb.Sdk;
using System;
using System.Collections.Generic;

namespace _10_Filmdatenbank.UnitTests.Services
{
    public class TvdbServiceTests
    {
        private readonly Mock<HttpMessageHandler> _handlerMock;
        private readonly HttpClient _httpClient;
        private readonly Mock<ILogger<TvdbService>> _loggerMock;
        private readonly Mock<IConfiguration> _configMock;
        private readonly TvdbService _service;

        public TvdbServiceTests()
        {
            _handlerMock = new Mock<HttpMessageHandler>();
            _httpClient = new HttpClient(_handlerMock.Object);
            _loggerMock = new Mock<ILogger<TvdbService>>();
            _configMock = new Mock<IConfiguration>();
            
            _configMock.Setup(c => c["TVDB:ApiKey"]).Returns("test-api-key");
            _service = new TvdbService(_configMock.Object, _httpClient, _loggerMock.Object);
        }

        [Fact]
        public async Task SearchMoviesAsync_Authenticates_And_Returns_Results()
        {
            // Arrange
            // 1. Mock Login Response
            var loginResponse = new LoginResponse { Status = "success", Data = new AuthToken { Token = "test-token" } };
            var searchResponse = new SearchResponse { Status = "success", Data = new List<SearchResult> { new SearchResult { Name = "Inception" } } };

            _handlerMock.Protected()
                .SetupSequence<Task<HttpResponseMessage>>("SendAsync", ItExpr.IsAny<HttpRequestMessage>(), ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK) { Content = JsonContent.Create(loginResponse) }) // Login
                .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK) { Content = JsonContent.Create(searchResponse) }); // Search

            // Act
            var results = await _service.SearchMoviesAsync("Inception");

            // Assert
            results.Should().NotBeEmpty();
            results.Should().ContainSingle(r => r.Name == "Inception");
            
            // Verify Authentication header was set (difficult to verify directly on the instance but we can check the calls)
        }

        [Fact]
        public async Task GetMovieDetailsAsync_Throws_WhenNotFound()
        {
            // Arrange
            var loginResponse = new LoginResponse { Status = "success", Data = new AuthToken { Token = "test-token" } };
            _handlerMock.Protected()
                .SetupSequence<Task<HttpResponseMessage>>("SendAsync", ItExpr.IsAny<HttpRequestMessage>(), ItExpr.IsAny<CancellationToken>())
                .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.OK) { Content = JsonContent.Create(loginResponse) }) // Login
                .ReturnsAsync(new HttpResponseMessage(HttpStatusCode.NotFound)); // Details

            // Act
            Func<Task> act = async () => await _service.GetMovieDetailsAsync(123);

            // Assert
            await act.Should().ThrowAsync<Exception>();
        }
    }

    // Helper classes normally generated by SDK but needed for mocking responses if assembly not fully visible/accessible for direct instantiation
    public class LoginResponse { public string? Status { get; set; } public AuthToken? Data { get; set; } }
    public class AuthToken { public string? Token { get; set; } }
    public class SearchResponse { public string? Status { get; set; } public List<SearchResult>? Data { get; set; } }
}
