// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10_Filmdatenbank.Infrastructure.Persistence;

#nullable disable

namespace _10_Filmdatenbank.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260313130827_GamificationAndFavorites")]
    partial class GamificationAndFavorites
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmGenres", b =>
                {
                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<int>("GenreID")
                        .HasColumnType("int");

                    b.HasKey("FilmID", "GenreID");

                    b.HasIndex("GenreID");

                    b.ToTable("FilmGenres", (string)null);
                });

            modelBuilder.Entity("FilmKeywords", b =>
                {
                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<int>("KeywordID")
                        .HasColumnType("int");

                    b.HasKey("FilmID", "KeywordID");

                    b.HasIndex("KeywordID");

                    b.ToTable("FilmKeywords", (string)null);
                });

            modelBuilder.Entity("FilmProductionCompanies", b =>
                {
                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<int>("ProductionCompanyID")
                        .HasColumnType("int");

                    b.HasKey("FilmID", "ProductionCompanyID");

                    b.HasIndex("ProductionCompanyID");

                    b.ToTable("FilmProductionCompanies", (string)null);
                });

            modelBuilder.Entity("FilmProductionCountries_ISO", b =>
                {
                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<string>("Iso_3166_1")
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("FilmID", "Iso_3166_1");

                    b.HasIndex("Iso_3166_1");

                    b.ToTable("FilmProductionCountries_ISO", (string)null);
                });

            modelBuilder.Entity("FilmRecommended", b =>
                {
                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<int>("RecommendedFilmID")
                        .HasColumnType("int");

                    b.HasKey("FilmID", "RecommendedFilmID");

                    b.HasIndex("RecommendedFilmID");

                    b.ToTable("FilmRecommended", (string)null);
                });

            modelBuilder.Entity("FilmSimilar", b =>
                {
                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<int>("SimilarFilmID")
                        .HasColumnType("int");

                    b.HasKey("FilmID", "SimilarFilmID");

                    b.HasIndex("SimilarFilmID");

                    b.ToTable("FilmSimilar", (string)null);
                });

            modelBuilder.Entity("FilmSpokenLanguages", b =>
                {
                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<string>("Iso_639_1")
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("FilmID", "Iso_639_1");

                    b.HasIndex("Iso_639_1");

                    b.ToTable("FilmSpokenLanguages", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Achievement", b =>
                {
                    b.Property<int>("AchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AchievementID"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AchievementID");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.AlternativeTitle", b =>
                {
                    b.Property<int>("AlternativeTitleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlternativeTitleID"));

                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<string>("Iso_3166_1")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlternativeTitleID");

                    b.HasIndex("FilmID");

                    b.ToTable("AlternativeTitles");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePictureContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Collection", b =>
                {
                    b.Property<int>("CollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionID"));

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("CollectionID");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("CommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentID"));

                    b.Property<string>("AuthorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ParentCommentID")
                        .HasColumnType("int");

                    b.Property<int>("ThreadID")
                        .HasColumnType("int");

                    b.HasKey("CommentID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("ParentCommentID");

                    b.HasIndex("ThreadID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Country", b =>
                {
                    b.Property<string>("Iso_3166_1")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Iso_3166_1");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.DiscussionThread", b =>
                {
                    b.Property<int>("ThreadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThreadID"));

                    b.Property<string>("AuthorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FanGroupID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ThreadID");

                    b.HasIndex("AuthorID");

                    b.HasIndex("FanGroupID");

                    b.ToTable("DiscussionThreads");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Eigenschaft", b =>
                {
                    b.Property<int>("EigenschaftID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EigenschaftID"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EigenschaftID");

                    b.ToTable("Eigenschaften");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.FanGroup", b =>
                {
                    b.Property<int>("FanGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FanGroupID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("GroupImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("GroupImageContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentGroupID")
                        .HasColumnType("int");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.HasKey("FanGroupID");

                    b.HasIndex("ParentGroupID");

                    b.ToTable("FanGroups");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.FavoriteFilm", b =>
                {
                    b.Property<int>("FavoriteFilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteFilmID"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FavoriteFilmID");

                    b.HasIndex("FilmID");

                    b.HasIndex("UserID");

                    b.ToTable("FavoriteFilms");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Film", b =>
                {
                    b.Property<int>("FilmID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmID"));

                    b.Property<bool>("Adult")
                        .HasColumnType("bit");

                    b.Property<string>("Awards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Budget")
                        .HasColumnType("bigint");

                    b.Property<int?>("CollectionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Erscheinungsdatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("Erscheinungsjahr")
                        .HasColumnType("int");

                    b.Property<string>("FacebookId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Handlung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Homepage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImdbId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Nutzerwertung")
                        .HasColumnType("float");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Popularity")
                        .HasColumnType("float");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("Revenue")
                        .HasColumnType("bigint");

                    b.Property<int>("Spieldauer")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tagline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("VoteAverage")
                        .HasColumnType("float");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("int");

                    b.Property<string>("WikidataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmID");

                    b.HasIndex("CollectionID");

                    b.ToTable("Filme");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.FilmRelease", b =>
                {
                    b.Property<int>("ReleaseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReleaseID"));

                    b.Property<string>("Certification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<string>("Iso_3166_1")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ReleaseID");

                    b.HasIndex("FilmID");

                    b.ToTable("FilmReleases");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("GenreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("GenreID");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.GroupBan", b =>
                {
                    b.Property<int>("GroupBanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupBanID"));

                    b.Property<DateTime>("BannedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FanGroupID")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GroupBanID");

                    b.HasIndex("FanGroupID");

                    b.HasIndex("UserID");

                    b.ToTable("GroupBans");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberID"));

                    b.Property<bool>("CanEditGroupContent")
                        .HasColumnType("bit");

                    b.Property<int>("FanGroupID")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GroupMemberID");

                    b.HasIndex("FanGroupID");

                    b.HasIndex("UserID");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Keyword", b =>
                {
                    b.Property<int>("KeywordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KeywordID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("KeywordID");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Language", b =>
                {
                    b.Property<string>("Iso_639_1")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NativeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Iso_639_1");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.MembershipRequest", b =>
                {
                    b.Property<int>("MembershipRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipRequestID"));

                    b.Property<int>("FanGroupID")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MembershipRequestID");

                    b.HasIndex("FanGroupID");

                    b.HasIndex("UserID");

                    b.ToTable("MembershipRequests");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"));

                    b.Property<bool>("Adult")
                        .HasColumnType("bit");

                    b.Property<string>("AlsoKnownAs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Awards")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Biografie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Deathday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacebookId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreebaseId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FreebaseMid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Geburtsdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Geburtsort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Homepage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImdbId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KnownForDepartment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Popularity")
                        .HasColumnType("float");

                    b.Property<string>("ProfilBildUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TmdbFilmographyJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("int");

                    b.Property<string>("TvrageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikidataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("Personen");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.PersonEigenschaftFilm", b =>
                {
                    b.Property<int>("PEFID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PEFID"));

                    b.Property<string>("Character")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EigenschaftID")
                        .HasColumnType("int");

                    b.Property<int>("FilmID")
                        .HasColumnType("int");

                    b.Property<string>("Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("PEFID");

                    b.HasIndex("EigenschaftID");

                    b.HasIndex("FilmID");

                    b.HasIndex("PersonID");

                    b.ToTable("PersonEigenschaftFilme");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.ProductionCompany", b =>
                {
                    b.Property<int>("ProductionCompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductionCompanyID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headquarters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Homepage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCompanyID")
                        .HasColumnType("int");

                    b.Property<int>("TmdbId")
                        .HasColumnType("int");

                    b.HasKey("ProductionCompanyID");

                    b.HasIndex("ParentCompanyID");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("ProductionCompanies");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<int>("UserAchievementID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserAchievementID"));

                    b.Property<int>("AchievementID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserAchievementID");

                    b.HasIndex("AchievementID");

                    b.HasIndex("UserID");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("FilmGenres", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenreID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmKeywords", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Keyword", null)
                        .WithMany()
                        .HasForeignKey("KeywordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmProductionCompanies", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ProductionCompany", null)
                        .WithMany()
                        .HasForeignKey("ProductionCompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmProductionCountries_ISO", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Country", null)
                        .WithMany()
                        .HasForeignKey("Iso_3166_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmRecommended", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("RecommendedFilmID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmSimilar", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("SimilarFilmID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("FilmSpokenLanguages", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Language", null)
                        .WithMany()
                        .HasForeignKey("Iso_639_1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.AlternativeTitle", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", "Film")
                        .WithMany("AlternativeTitles")
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Comment", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.DiscussionThread", "Thread")
                        .WithMany("Comments")
                        .HasForeignKey("ThreadID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.DiscussionThread", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", "Author")
                        .WithMany("Threads")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.FanGroup", "FanGroup")
                        .WithMany("Threads")
                        .HasForeignKey("FanGroupID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("FanGroup");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.FanGroup", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.FanGroup", "ParentGroup")
                        .WithMany("SubGroups")
                        .HasForeignKey("ParentGroupID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.FavoriteFilm", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", "User")
                        .WithMany("FavoriteFilms")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Film", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Collection", "Collection")
                        .WithMany("Films")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.FilmRelease", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", "Film")
                        .WithMany("Releases")
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.GroupBan", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.FanGroup", "FanGroup")
                        .WithMany("BannedUsers")
                        .HasForeignKey("FanGroupID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FanGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.FanGroup", "FanGroup")
                        .WithMany("Members")
                        .HasForeignKey("FanGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FanGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.MembershipRequest", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.FanGroup", "FanGroup")
                        .WithMany("JoinRequests")
                        .HasForeignKey("FanGroupID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FanGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Notification", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.PersonEigenschaftFilm", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Eigenschaft", "Eigenschaft")
                        .WithMany("PersonEigenschaftFilme")
                        .HasForeignKey("EigenschaftID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Film", "Film")
                        .WithMany("PersonEigenschaftFilme")
                        .HasForeignKey("FilmID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Person", "Person")
                        .WithMany("PersonEigenschaftFilme")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eigenschaft");

                    b.Navigation("Film");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.ProductionCompany", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ProductionCompany", "ParentCompany")
                        .WithMany()
                        .HasForeignKey("ParentCompanyID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCompany");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("_10_Filmdatenbank.Domain.Entities.Achievement", "Achievement")
                        .WithMany("EarnedBy")
                        .HasForeignKey("AchievementID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_10_Filmdatenbank.Domain.Entities.ApplicationUser", "User")
                        .WithMany("EarnedAchievements")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Achievement", b =>
                {
                    b.Navigation("EarnedBy");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("EarnedAchievements");

                    b.Navigation("FavoriteFilms");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Notifications");

                    b.Navigation("Threads");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Films");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.DiscussionThread", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Eigenschaft", b =>
                {
                    b.Navigation("PersonEigenschaftFilme");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.FanGroup", b =>
                {
                    b.Navigation("BannedUsers");

                    b.Navigation("JoinRequests");

                    b.Navigation("Members");

                    b.Navigation("SubGroups");

                    b.Navigation("Threads");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Film", b =>
                {
                    b.Navigation("AlternativeTitles");

                    b.Navigation("PersonEigenschaftFilme");

                    b.Navigation("Releases");
                });

            modelBuilder.Entity("_10_Filmdatenbank.Domain.Entities.Person", b =>
                {
                    b.Navigation("PersonEigenschaftFilme");
                });
#pragma warning restore 612, 618
        }
    }
}
